name: Smoke test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        mkdir build && cd build && cmake ..
    - name: build
      run: |
        make -j4
    - name: test
      run: | 
        ctest -V
